### ISSUE TITLE
Add init function for structs

### ISSUE THREAD

**Issue by SupunS** [ballerina-lang/ballerina#4340]
Needs a struct init function, which will get called by default when a struct value is created.
This is useful to initialize nested structs (or to give default values to ref-type fields), without having to manually initialize each and every field, everytime a value is created.

**Comment by sameera-jayasoma** [comment]
A struct initializer is a block of code wrapped in a function that's called when a struct instance is created (using the struct literal expression '{}' ).  The struct initializer function name should be equal to the struct name and this function cannot accept any input parameters or return types.

struct person {
    int age = 20;
    string name;
    string address;
}

// This is the struct initializer. 
// Function name is equal to the struct name.
function <person p> person() {
    p.age = 10;
    p.name = "Charles";
}

// An attached function to the struct 'person'
function <person p> getAge() {
    p.age = 12;
}

**Comment by sanjiva** [comment]
Sameera shall we remove field initialization capability with this?

fieldDefinition
    :   typeName Identifier (ASSIGN simpleLiteral)? SEMICOLON
    ;

Without that there's some weirdness ... e.g. in your example above you've set age to 20 at declaration time and then to 10 at init time.  Its not clear what age is in "person x = {}" now.

We don't need both .. since we need the initializer shall we remove field initialization?

**Comment by sanjiva** [comment]
Also, what's the execution order for this:
```
struct foo { int x = 10; }

function<foo f> foo () { 
  println (x);
  f.x = 11;
}
main() { 
  foo f0 = {};
  println ("f0"); // == 10
  println (f0.x); // == 11

  foo f1 = { x = 12; }
  println ("f1"); // == 12
  println (f1.x); // == 11
}
```

Is my assumption correct?

**Comment by sameera-jayasoma** [comment]
Hi Sanjiva, 

Yes, your assumptions are correct.

```ballerina
struct foo { int x = 10; }

function<foo f> foo () { 
  println (x);
  f.x = 11;
}

main() { 
  foo f0 = {};
  println ("f0"); // == 10
  println (f0.x); // == 11

  foo f1 = { x = 12; }
  println ("f1"); // == 12
  println (f1.x); // == 11
}
```

Here is the output
```
10
f0
11
12
f1
11
```

**Comment by hasithaa** [comment]
@sameera-jayasoma @sanjiva 

```ballerina
import ballerina.io;

struct foo { int x = 10; }

function <foo f> foo () {
    io:println(f.x);
    f.x = 11;
}

function main (string[] args) {
    foo f0 = {}; // == 10
    io:print("f0 "); 
    io:println(f0.x); // == 11

    foo f1 = {x:12}; // == 12
    io:print("f1 ");
    io:println(f1.x); // == 11
}
```

I don't think, this above behavior is correct. The Issue is the value of `{x:12}` is replaced by the constructor. Correct execution should be, 

1. call struct initializer. 
2. then copy values of struct init literal.

Otherwise, the developer has to write another line to set x's value to 12.
 
```
 foo f1 = {};
 f1.x = 12;
```
